dist: trusty
sudo: required

services: docker

language: bash

branches:
  only:
    - master

before_script:
  - env | sort
  - name="mautic"
  - image="monogramm/docker-mautic:${VERSION}${VARIANT:+-$VARIANT}"
  - dir="images/${VERSION}${VARIANT:+-$VARIANT}"

script:
  - travis_retry docker build -t "$image" "$dir"
  - docker images
  - docker run --name percona -d -p 3306:3306 -e MYSQL_ROOT_PASSWORD=mypassword -v mysql_data:/var/lib/mysql percona/percona-server:5.7 --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
  - docker run --name "$name" -d -p 8080:80 -v ./html:/var/www/html -e MAUTIC_DB_HOST=percona:3306 -e MAUTIC_DB_USER=root -e MAUTIC_DB_NAME=mautic -e MAUTIC_DB_PASSWORD=mypassword "$image"
  - ls ./html/plugins

after_script:
  - docker ps
  - docker logs "$name"

notifications:
  email: false

env: # Environments
    - VERSION=2.15 VARIANT=fpm
    - VERSION=2.15 VARIANT=apache
