dist: trusty
sudo: required

services: docker

language: bash

branches:
  only:
    - master

before_script:
  - env | sort
  - name="mautic"
  - image="monogramm/docker-mautic:${VERSION}${VARIANT:+-$VARIANT}"
  - dir="images/${VERSION}${VARIANT:+-$VARIANT}"

script:
  - cd "$dir"
  - docker-compose build
  - docker images
  - travis_retry docker-compose up -d && sleep 300
  - docker-compose ps
  - docker-compose logs
  - docker-compose ps "mauticdb" | grep "Up"
  - docker-compose ps "mautic" | grep "Up"
  - grep "monogramm/mautic-ldapauth-bundle" /srv/mautic/html/composer.json

after_script:
  - ls /srv/mautic/html/plugins
  - ls /srv/mautic/html/plugins/MauticLdapauthBundle

notifications:
  email: false

env: # Environments
    - VERSION=2.15 VARIANT=fpm
    - VERSION=2.15 VARIANT=apache
