os: linux
dist: bionic

services: docker

language: shell

branches:
  only:
    - master

before_script:
  - env | sort
  - dir="images/${VERSION}${VARIANT:+-$VARIANT}"

script:
  - cd "$dir"
  - docker-compose build
  - docker images
  - travis_retry docker-compose up -d && sleep 300
  - docker-compose ps
  - docker-compose logs
  - docker-compose ps "mauticdb" | grep "Up"
  - docker-compose ps "mautic" | grep "Up"
  - grep "monogramm/mautic-ldap-auth-bundle" /srv/mautic/html/composer.json
  - ls /srv/mautic/html/plugins

after_script:
  - ls /srv/mautic/html/plugins/MauticLdapauthBundle

notifications:
  email: false

  jobs:
    allow_failures:
      - env: VERSION=3.0 VARIANT=fpm
      - env: VERSION=3.0 VARIANT=apache

env: # Environments
    - VERSION=2.15 VARIANT=fpm
    - VERSION=2.15 VARIANT=apache
    - VERSION=2.16 VARIANT=fpm
    - VERSION=2.16 VARIANT=apache
    - VERSION=3.0 VARIANT=fpm
    - VERSION=3.0 VARIANT=apache
