#!/bin/bash

# See documentation for details:
# https://docs.docker.com/docker-hub/builds/advanced/

for file in docker-compose*.test.yml; do

    echo "TODO Starting Test in ${file}..."

    # Build test container
    docker-compose --no-ansi -f "${file}" build sut
    # Test container run
    docker-compose --no-ansi -f "${file}" up -d && sleep 60
    #docker-compose --no-ansi -f "${file}" logs -f "sut"
    docker-compose --no-ansi -f "${file}" ps
    docker-compose --no-ansi -f "${file}" logs "mauticdb"
    docker-compose --no-ansi -f "${file}" ps "mauticdb" | grep "Up"
    docker-compose --no-ansi -f "${file}" logs "mautic"
    docker-compose --no-ansi -f "${file}" ps "mautic" | grep "Up"
    #docker-compose --no-ansi -f "${file}" ps "sut" | grep "Exit 0" || exit 1
    docker-compose --no-ansi -f "${file}" down
    # Test container restart
    docker-compose --no-ansi -f "${file}" up -d && sleep 60
    #docker-compose --no-ansi -f "${file}" logs -f "sut"
    docker-compose --no-ansi -f "${file}" ps
    docker-compose --no-ansi -f "${file}" logs "mauticdb"
    docker-compose --no-ansi -f "${file}" ps "mauticdb" | grep "Up"
    docker-compose --no-ansi -f "${file}" logs "mautic"
    docker-compose --no-ansi -f "${file}" ps "mautic" | grep "Up"
    #docker-compose --no-ansi -f "${file}" ps "sut" | grep "Exit 0" || exit 1
    docker-compose --no-ansi -f "${file}" down --volumes

done
